name: Build and Release

on:
    release:
        types: [published]

jobs:
    goreleaser:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - uses: actions/setup-go@v4
              with:
                  go-version: 1.22

            - uses: goreleaser/goreleaser-action@v4
              with:
                  distribution: goreleaser
                  version: latest
                  args: release --clean
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
