name: Build to Execute File

on:
    release:
        types: [published]

jobs:
    goreleaser:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: actions/setup-go@v5
              with:
                  go-version: ^1.22
            - run: go version

            - uses: goreleaser/goreleaser-action@v5
              with:
                  distribution: goreleaser
                  version: latest
                  args: release --clean
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
